=== TrellixVulnTeam/flaskapps_LK3A/repos/machine-learning-master/interface/static/data/xml/svr.xsd
<?xml version='1.0'?>

<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
  <xs:element name='dataset'>
    <xs:complexType>

      <xs:sequence>
        <xs:element name='observation' maxOccurs='unbounded'>
          <xs:complexType>

            <xs:sequence>
              <xs:element name='dependent-variable' type='xs:string'/>
              <xs:element name='independent-variable' maxOccurs='unbounded'>

                <xs:complexType>
                  <xs:sequence>
                    <xs:element name='label' type='xs:string'/>
                    <xs:element name='value' type='xs:decimal'/>
                  </xs:sequence>
                </xs:complexType>

              </xs:element>
            </xs:sequence>

           </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== TrellixVulnTeam/flaskapps_LK3A/repos/machine-learning-master/interface/static/data/xml/svr.xml
<?xml version='1.0'?>

<dataset xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
xsi:noNamespaceSchemaLocation='https://github.com/jeff1evesque/machine-learning/tree/master/interface/static/data/xml/svr.xsd'>
  <observation>
    <dependent-variable>34.332</dependent-variable>
    <independent-variable>
      <label>independent-variable-1</label>
      <value>23.45</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-2</label>
      <value>98.01</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-3</label>
      <value>0.432</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-4</label>
      <value>325</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-5</label>
      <value>54.64</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-6</label>
      <value>0.002</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-7</label>
      <value>25</value>
    </independent-variable>
  </observation>

  <observation>
    <dependent-variable >45.873</dependent-variable>
    <independent-variable>
      <label>independent-variable-1</label>
      <value>24.32</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-2</label>
      <value>92.22</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-3</label>
      <value>0.356</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-4</label>
      <value>235</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-5</label>
      <value>64.45</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-6</label>
      <value>0.001</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-7</label>
      <value>31</value>
    </independent-variable>
  </observation>

  <observation>
    <dependent-variable>36.183</dependent-variable>
    <independent-variable>
      <label>independent-variable-1</label>
      <value>22.67</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-2</label>
      <value>101.21</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-3</label>
      <value>0.832</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-4</label>
      <value>427</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-5</label>
      <value>75.45</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-6</label>
      <value>0.002</value>
    </independent-variable>
    <independent-variable>
      <label>independent-variable-7</label>
      <value>24</value>
    </independent-variable>
  </observation>
</dataset>
